server {
    # Listen to port 443 on both IPv4 and IPv6.
    listen 443 ssl default_server reuseport;
    listen [::]:443 ssl default_server reuseport;

    # Domain names this server should respond to.
    server_name mmclue.com www.mmclue.com;


    # common.conf
    # Load the ECDSA certificates.
    ssl_certificate /etc/letsencrypt/live/aliyun-ecc/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aliyun-ecc/privkey.pem;

    # Load the RSA certificates.
    ssl_certificate /etc/letsencrypt/live/aliyun-rsa/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aliyun-rsa/privkey.pem;

    # Load the Diffie-Hellman parameter.
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;
    # Load the ssl_ecdh_curve parameter.
    ssl_ecdh_curve X25519:prime256v1;

    # Define the ciphers to use in the preferred order.
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:DHE+AESGCM:DHE:!RSA!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!CAMELLIA:!SEED";

    if ($request_method = CONNECT) {
        return 444;
    }

    # 阻挡常见扫描路径
    location ~* /(wordpress|wp-admin|wiki|wp-login\.php|xmlrpc\.php|phpmyadmin|config\.php|setup\.php|shell\.php|vendor/phpunit|cgi-bin|backup\.zip|admin\.php|upload\.php|readme\.html|install\.php|phpinfo\.php|robots\.txt|sitemap\.xml|config\.json|wlwmanifest\.xml) {
        access_log off;
        return 444;
    }

    # 禁止访问隐藏文件和目录（如 .git）
    location ~ /\. {
        access_log off;
        return 444;
    }

    # 防止访问备份文件等
    location ~* \.(bak|config|sql|fla|psd|ini|log|sh|inc|swp|dist)$ {
        access_log off;
        return 444;
    }

    # 处理 favicon.ico，避免大量404日志
    location = /favicon.ico {
        access_log off;
        log_not_found off;
        # 指向你实际存在的 favicon 文件路径，或者用空文件替代
        try_files /favicon.ico =204;
    }

    # 默认响应
    location / {
        root /usr/share/nginx/html; # 替换为你的网页根目录
        index index.html index.htm;
        try_files $uri $uri/ =404;
    }

}
