map $request_uri $bad_uri {
    default 0;
    ~[\x00-\x08\x0B\x0C\x0E-\x1F\x7F-\xFF] 1;
}

map $http_user_agent $bad_ua {
    "" 1;
    default 0;
}

server {
    listen 443 ssl default_server reuseport;
    listen [::]:443 ssl default_server reuseport;

    server_name mmclue.com www.mmclue.com;

    # 如果不是 mmclue.com 或其子域名，直接返回 444
    if ($host !~* ^(.*\.)?mmclue\.com$) {
        return 444;
    }

    # SSL 证书
    ssl_certificate /etc/letsencrypt/live/aliyun-ecc/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aliyun-ecc/privkey.pem;

    ssl_certificate /etc/letsencrypt/live/aliyun-rsa/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aliyun-rsa/privkey.pem;

    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;
    ssl_ecdh_curve X25519:prime256v1;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:DHE+AESGCM:DHE:!RSA!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!CAMELLIA:!SEED";


    # 请求方法限制，放最前面
    if ($request_method = CONNECT) {
        return 444;
    }

    # favicon 特殊处理
    location = /favicon.ico {
        access_log off;
        log_not_found off;
        try_files /favicon.ico =204;
    }

    # 限制请求体大小
    client_max_body_size 1M;

    # 默认根目录响应
    location = / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ =404;
        return 200;
    }
    location / {
        access_log off;
        return 444;
    }
}
